// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backdog.proto

package backdog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// type req struct {
//    Uid        int      `json:"uid"`        // 调用者的UID
//    Command    []string `json:"command"`    // 执行的命令
//    Background bool     `json:"background"` // 0 前台运行，1 后台运行
//    Timeout    int      `json:"timeout"`    // 超时时间，秒
//    Timestamp  int64    `json:"timestamp"`  // 时间戳，秒
// }
type Request struct {
	Command              string   `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_backdog_b5e2454185e98cc3, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type Response struct {
	Stdout               []byte   `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte   `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_backdog_b5e2454185e98cc3, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *Response) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "backdog.Request")
	proto.RegisterType((*Response)(nil), "backdog.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExecClient is the client API for Exec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExecClient interface {
	Command(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type execClient struct {
	cc *grpc.ClientConn
}

func NewExecClient(cc *grpc.ClientConn) ExecClient {
	return &execClient{cc}
}

func (c *execClient) Command(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/backdog.Exec/Command", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecServer is the server API for Exec service.
type ExecServer interface {
	Command(context.Context, *Request) (*Response, error)
}

func RegisterExecServer(s *grpc.Server, srv ExecServer) {
	s.RegisterService(&_Exec_serviceDesc, srv)
}

func _Exec_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backdog.Exec/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecServer).Command(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Exec_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backdog.Exec",
	HandlerType: (*ExecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Command",
			Handler:    _Exec_Command_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backdog.proto",
}

func init() { proto.RegisterFile("backdog.proto", fileDescriptor_backdog_b5e2454185e98cc3) }

var fileDescriptor_backdog_b5e2454185e98cc3 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xad, 0xae, 0x1b, 0x1d, 0x56, 0xd0, 0x20, 0x12, 0x3c, 0x69, 0xbd, 0x78, 0x2a, 0xe2,
	0x5e, 0x3c, 0x57, 0xbd, 0x2f, 0xf9, 0x07, 0xd9, 0x64, 0xc8, 0x6a, 0x6d, 0xa6, 0x4e, 0x52, 0xf0,
	0xe7, 0x4b, 0x9b, 0x54, 0x3c, 0x7e, 0x8f, 0x61, 0xde, 0xc7, 0x83, 0x8b, 0xbd, 0xb1, 0x9d, 0x23,
	0xdf, 0x0c, 0x4c, 0x89, 0xa4, 0x28, 0x58, 0x3f, 0x80, 0xd0, 0xf8, 0x3d, 0x62, 0x4c, 0x52, 0x81,
	0xb0, 0xd4, 0xf7, 0x26, 0x38, 0x55, 0xdd, 0x55, 0x8f, 0xe7, 0x7a, 0xc1, 0xfa, 0x13, 0xce, 0x34,
	0xc6, 0x81, 0x42, 0x44, 0x79, 0x03, 0xeb, 0x98, 0x1c, 0x8d, 0x69, 0x3e, 0xda, 0xe8, 0x42, 0x25,
	0x47, 0x66, 0x75, 0xfc, 0x97, 0x23, 0xb3, 0xbc, 0x86, 0x53, 0x64, 0x26, 0x56, 0x27, 0xf3, 0xcf,
	0x0c, 0x53, 0x57, 0x8f, 0x31, 0x1a, 0x8f, 0x6a, 0x95, 0xbb, 0x0a, 0x3e, 0xbf, 0xc0, 0xea, 0xfd,
	0x07, 0xad, 0x7c, 0x02, 0xf1, 0x9a, 0xeb, 0xe5, 0x65, 0xb3, 0xc8, 0x17, 0xd5, 0xdb, 0xab, 0x7f,
	0x49, 0xf6, 0xaa, 0x8f, 0xda, 0x2d, 0xdc, 0x07, 0x4c, 0x0d, 0x05, 0x4c, 0x87, 0x8f, 0xe0, 0x13,
	0xda, 0xc3, 0x04, 0xf6, 0x8b, 0x46, 0xb7, 0xdc, 0xb7, 0x9b, 0xd6, 0xd8, 0xee, 0x8d, 0xfc, 0x6e,
	0x9a, 0x61, 0x57, 0xed, 0xd7, 0xf3, 0x1e, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0x3f,
	0x8b, 0x12, 0x20, 0x01, 0x00, 0x00,
}
